const clientsData = [
  {
    name: "Rahul Singh",
    project: "Twin Chalet",
    type: "Flat",
    config: "3BHK, A-105",
    status: "Complete",
    amount: "₹ 1.36 Cr",
    received: "₹ 12.5 Lakh",
    sales: "Nihal Singh",
  },
  {
    name: "Amit Sharma",
    project: "Green Valley",
    type: "Flat",
    config: "2BHK, B-203",
    status: "Pending",
    amount: "₹ 75 Lakh",
    received: "₹ 40 Lakh",
    sales: "Rohit Verma",
  },
  {
    name: "Priya Verma",
    project: "Sunshine Residency",
    type: "Flat",
    config: "3BHK, C-110",
    status: "Complete",
    amount: "₹ 95 Lakh",
    received: "₹ 95 Lakh",
    sales: "Ankit Gupta",
  },
  {
    name: "Vikas Yadav",
    project: "Royal Enclave",
    type: "Villa",
    config: "NA",
    status: "Pending",
    amount: "₹ 2.1 Cr",
    received: "₹ 1.2 Cr",
    sales: "Nihal Singh",
  },
  {
    name: "Sneha Patel",
    project: "Sky Heights",
    type: "Flat",
    config: "2BHK, D-404",
    status: "Complete",
    amount: "₹ 68 Lakh",
    received: "₹ 68 Lakh",
    sales: "Rohit Verma",
  },
  {
    name: "Karan Mehta",
    project: "Palm Residency",
    type: "Flat",
    config: "1BHK, A-101",
    status: "Pending",
    amount: "₹ 45 Lakh",
    received: "₹ 20 Lakh",
    sales: "Ankit Gupta",
  },
  {
    name: "Neha Gupta",
    project: "Lake View",
    type: "Villa",
    config: "NA",
    status: "Complete",
    amount: "₹ 1.8 Cr",
    received: "₹ 1.8 Cr",
    sales: "Nihal Singh",
  },
  {
    name: "Rohit Kumar",
    project: "Urban Nest",
    type: "Flat",
    config: "2BHK, B-210",
    status: "Pending",
    amount: "₹ 82 Lakh",
    received: "₹ 50 Lakh",
    sales: "Rohit Verma",
  },
  {
    name: "Pooja Singh",
    project: "Elite Homes",
    type: "Flat",
    config: "3BHK, E-305",
    status: "Complete",
    amount: "₹ 1.1 Cr",
    received: "₹ 1.1 Cr",
    sales: "Ankit Gupta",
  },
  {
    name: "Arjun Das",
    project: "City Square",
    type: "Flat",
    config: "2BHK, F-502",
    status: "Pending",
    amount: "₹ 90 Lakh",
    received: "₹ 60 Lakh",
    sales: "Nihal Singh",
  },
];
export { clientsData };